### ISSUE TITLE
Box Field Creation not setting Fields data

### ISSUE THREAD

**Issue by princecharmx** [StreakYC/node-api-wrapper#10]
This code, cud not generate values for fileds with key 1002. It only set data for name and notes.
Tried double-checking the field key but no success.
```
 var datai = {name: "NewlyNamedBox2", notes: "AdditionalNotesText",
      "fields":  {"key": "1002", "value": "Some string"}} ;

streak.Boxes.create(pipelineKey, datai).then(function(data) {
      console.log("pipeline4 :" + util.inspect(data, {showHidden: false, depth: null}));
    });
```

**Comment by AgentME** [comment]
Currently you need to use the `streak.Pipelines.Fields.*` methods to manipulate the fields sub-object of a box.
