### ISSUE TITLE
How to handle error

### ISSUE THREAD

**Issue by princecharmx** [StreakYC/node-api-wrapper#11]
Hi,

The streakapi does not return when there is an error. How to handle error response.

From example, I cud figure out how data is received but need help with error as well.

**Comment by princecharmx** [comment]
@AgentME  & @omarstreak can u help plz

**Comment by AgentME** [comment]
All of the functions return [promise objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). You can handle errors like this: 

```js
streak.Me.get().then(function(me) {
  console.log('email', me.email);
}).catch(function(err) {
  console.error('got an error', err);
});
```

**Comment by princecharmx** [comment]
wow tht was lightening speed response/ Thanks a lot @AgentME
