### ISSUE TITLE
How to get streak tasks

### ISSUE THREAD

**Issue by princecharmx** [StreakYC/node-api-wrapper#12]
Hi @AgentME ,

How to create and get tasks associated with a streak box. There is no api like fields and threads have, for tasks

**Comment by aleemstreak** [comment]
sorry this isn't part of the library yet, we'd be happy to accept pull
requests

**Comment by princecharmx** [comment]
okay, will do tht. Thx

**Comment by AgentME** [comment]
Fixed by #14.
