### ISSUE TITLE
Boxes.update() incorrect params

### ISSUE THREAD

**Issue by noahbornstein** [StreakYC/node-api-wrapper#9]
Looks like `streak.Boxes.update(data);` should have `boxKey` as the first param. (Might just need to update Readme...)

**Comment by princecharmx** [comment]
@noahbornstein , were you able to get box.create working with fields data?

**Comment by noahbornstein** [comment]
@princecharmx yes, the following worked:
```boxData = {
        name: companyName,
        notes: "...",
        pipelineKey: "..."
    };
streak.Boxes.create(boxData.pipelineKey, boxData).then(function(data){
...
});```

**Comment by AgentME** [comment]
Sorry for not answering this sooner! The data object passed to `Boxes.update` needs to have a key property.
